# Generated by Django 4.0 on 2021-12-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('course_number', models.IntegerField()),
                ('instructor', models.CharField(max_length=60)),
                ('duration', models.FloatField()),
            ],
        ),
    ]
